services:
  db:
    image: 'mysql:5.7'
    container_name: db
    command: '--init-file /docker-entrypoint-initdb.d/init.sql'
    volumes:
      - './dbfile:/var/lib/mysql'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '3308:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'somepassw'
  server:
    image: 'server'
    container_name: server
    ports:
      - '8000:80'
    volumes:
      - './src:/var/www/html'
    depends_on:
      - db
  client:
    image: 'client'
    container_name: client
    command: ''
